### ISSUE TITLE
Highway to GeoNature conference

### ISSUE THREAD

**Issue by jacquesfize** [jacquesfize/gn_mapping_geonature#1]
L'objectif est de développer un module GeoNature de démonstration pour l'atelier architecture des Journées GeoNature 2024.

## TODO LIST

- [x] Faire une table `organisme` dans le schema `pr_mapping_geonature`
  - [x] Champs :  `id_organisme`, `nom`, `description`, `type_organisme`,`url`, `geometry`
- [x] Faire une table `bib_type_organisme` contenant les différents types d'organismes
- [x] Faire les schémas Marshmallow
- [x] Faire les modèles SQLAlchemy
- [x] Page
   - [x] carte +liste (home)
   - [x] ajout organisme
   - [x] édition
   - [x] détail
- [x] Migrations alembic 
   - [x] création base
   - [ ]  remplissage données réelles
- [x] routes flask
   - [x] PUT organisme(update) **!!A TESTER avec le frontend!!**
   - [x] GET organisme (get)
   - [x] DELETE organisme (delete)
   - [x] POST organisme (add) **!!A TESTER avec le frontend!!**
